(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> 'Table' object has no attribute 'created'"
p3
sS'layer'
p4
S'E:\\web2py\\applications\\reddit_clone\\controllers/default.py'
p5
sS'code'
p6
S'<code object <module> at 082DD140, file "E:\\web2py\\applications\\reddit_clone\\controllers/default.py", line 17>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "E:\\web2py\\gluon\\restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "E:\\web2py\\applications\\reddit_clone\\controllers/default.py", line 132, in <module>\n  File "E:\\web2py\\gluon\\globals.py", line 419, in <lambda>\n    self._caller = lambda f: f()\n  File "E:\\web2py\\applications\\reddit_clone\\controllers/default.py", line 33, in create_post\n    db.post.created.default = category.id\nAttributeError: \'Table\' object has no attribute \'created\'\n'
p11
s.